// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logistica.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Producto             string   `protobuf:"bytes,2,opt,name=producto,proto3" json:"producto,omitempty"`
	Valor                int64    `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Tienda               string   `protobuf:"bytes,4,opt,name=tienda,proto3" json:"tienda,omitempty"`
	Destino              string   `protobuf:"bytes,5,opt,name=destino,proto3" json:"destino,omitempty"`
	Tipo                 string   `protobuf:"bytes,6,opt,name=tipo,proto3" json:"tipo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcfa1b9154291741, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetProducto() string {
	if m != nil {
		return m.Producto
	}
	return ""
}

func (m *Order) GetValor() int64 {
	if m != nil {
		return m.Valor
	}
	return 0
}

func (m *Order) GetTienda() string {
	if m != nil {
		return m.Tienda
	}
	return ""
}

func (m *Order) GetDestino() string {
	if m != nil {
		return m.Destino
	}
	return ""
}

func (m *Order) GetTipo() string {
	if m != nil {
		return m.Tipo
	}
	return ""
}

type Register struct {
	Timestamp            string   `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IdPacket             string   `protobuf:"bytes,2,opt,name=idPacket,proto3" json:"idPacket,omitempty"`
	Tipo                 string   `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Nombre               string   `protobuf:"bytes,4,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Valor                int64    `protobuf:"varint,5,opt,name=valor,proto3" json:"valor,omitempty"`
	Origen               string   `protobuf:"bytes,6,opt,name=origen,proto3" json:"origen,omitempty"`
	Destino              string   `protobuf:"bytes,7,opt,name=destino,proto3" json:"destino,omitempty"`
	Seguimiento          int64    `protobuf:"varint,8,opt,name=seguimiento,proto3" json:"seguimiento,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Register) Reset()         { *m = Register{} }
func (m *Register) String() string { return proto.CompactTextString(m) }
func (*Register) ProtoMessage()    {}
func (*Register) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcfa1b9154291741, []int{1}
}

func (m *Register) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Register.Unmarshal(m, b)
}
func (m *Register) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Register.Marshal(b, m, deterministic)
}
func (m *Register) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Register.Merge(m, src)
}
func (m *Register) XXX_Size() int {
	return xxx_messageInfo_Register.Size(m)
}
func (m *Register) XXX_DiscardUnknown() {
	xxx_messageInfo_Register.DiscardUnknown(m)
}

var xxx_messageInfo_Register proto.InternalMessageInfo

func (m *Register) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Register) GetIdPacket() string {
	if m != nil {
		return m.IdPacket
	}
	return ""
}

func (m *Register) GetTipo() string {
	if m != nil {
		return m.Tipo
	}
	return ""
}

func (m *Register) GetNombre() string {
	if m != nil {
		return m.Nombre
	}
	return ""
}

func (m *Register) GetValor() int64 {
	if m != nil {
		return m.Valor
	}
	return 0
}

func (m *Register) GetOrigen() string {
	if m != nil {
		return m.Origen
	}
	return ""
}

func (m *Register) GetDestino() string {
	if m != nil {
		return m.Destino
	}
	return ""
}

func (m *Register) GetSeguimiento() int64 {
	if m != nil {
		return m.Seguimiento
	}
	return 0
}

type Packet struct {
	IdPacket             string   `protobuf:"bytes,1,opt,name=idPacket,proto3" json:"idPacket,omitempty"`
	Seguimiento          int64    `protobuf:"varint,2,opt,name=seguimiento,proto3" json:"seguimiento,omitempty"`
	Tipo                 string   `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Valor                int64    `protobuf:"varint,4,opt,name=valor,proto3" json:"valor,omitempty"`
	Intentos             int64    `protobuf:"varint,5,opt,name=intentos,proto3" json:"intentos,omitempty"`
	Estado               string   `protobuf:"bytes,6,opt,name=estado,proto3" json:"estado,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcfa1b9154291741, []int{2}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetIdPacket() string {
	if m != nil {
		return m.IdPacket
	}
	return ""
}

func (m *Packet) GetSeguimiento() int64 {
	if m != nil {
		return m.Seguimiento
	}
	return 0
}

func (m *Packet) GetTipo() string {
	if m != nil {
		return m.Tipo
	}
	return ""
}

func (m *Packet) GetValor() int64 {
	if m != nil {
		return m.Valor
	}
	return 0
}

func (m *Packet) GetIntentos() int64 {
	if m != nil {
		return m.Intentos
	}
	return 0
}

func (m *Packet) GetEstado() string {
	if m != nil {
		return m.Estado
	}
	return ""
}

type QuerySeguimiento struct {
	Seguimiento          int64    `protobuf:"varint,1,opt,name=seguimiento,proto3" json:"seguimiento,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuerySeguimiento) Reset()         { *m = QuerySeguimiento{} }
func (m *QuerySeguimiento) String() string { return proto.CompactTextString(m) }
func (*QuerySeguimiento) ProtoMessage()    {}
func (*QuerySeguimiento) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcfa1b9154291741, []int{3}
}

func (m *QuerySeguimiento) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySeguimiento.Unmarshal(m, b)
}
func (m *QuerySeguimiento) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySeguimiento.Marshal(b, m, deterministic)
}
func (m *QuerySeguimiento) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySeguimiento.Merge(m, src)
}
func (m *QuerySeguimiento) XXX_Size() int {
	return xxx_messageInfo_QuerySeguimiento.Size(m)
}
func (m *QuerySeguimiento) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySeguimiento.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySeguimiento proto.InternalMessageInfo

func (m *QuerySeguimiento) GetSeguimiento() int64 {
	if m != nil {
		return m.Seguimiento
	}
	return 0
}

type ReplySeguimiento struct {
	Estado               string   `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplySeguimiento) Reset()         { *m = ReplySeguimiento{} }
func (m *ReplySeguimiento) String() string { return proto.CompactTextString(m) }
func (*ReplySeguimiento) ProtoMessage()    {}
func (*ReplySeguimiento) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcfa1b9154291741, []int{4}
}

func (m *ReplySeguimiento) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplySeguimiento.Unmarshal(m, b)
}
func (m *ReplySeguimiento) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplySeguimiento.Marshal(b, m, deterministic)
}
func (m *ReplySeguimiento) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplySeguimiento.Merge(m, src)
}
func (m *ReplySeguimiento) XXX_Size() int {
	return xxx_messageInfo_ReplySeguimiento.Size(m)
}
func (m *ReplySeguimiento) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplySeguimiento.DiscardUnknown(m)
}

var xxx_messageInfo_ReplySeguimiento proto.InternalMessageInfo

func (m *ReplySeguimiento) GetEstado() string {
	if m != nil {
		return m.Estado
	}
	return ""
}

type ReadyAdvice struct {
	Tipo                 string   `protobuf:"bytes,1,opt,name=tipo,proto3" json:"tipo,omitempty"`
	UltRet               bool     `protobuf:"varint,2,opt,name=ult_ret,json=ultRet,proto3" json:"ult_ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadyAdvice) Reset()         { *m = ReadyAdvice{} }
func (m *ReadyAdvice) String() string { return proto.CompactTextString(m) }
func (*ReadyAdvice) ProtoMessage()    {}
func (*ReadyAdvice) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcfa1b9154291741, []int{5}
}

func (m *ReadyAdvice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadyAdvice.Unmarshal(m, b)
}
func (m *ReadyAdvice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadyAdvice.Marshal(b, m, deterministic)
}
func (m *ReadyAdvice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadyAdvice.Merge(m, src)
}
func (m *ReadyAdvice) XXX_Size() int {
	return xxx_messageInfo_ReadyAdvice.Size(m)
}
func (m *ReadyAdvice) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadyAdvice.DiscardUnknown(m)
}

var xxx_messageInfo_ReadyAdvice proto.InternalMessageInfo

func (m *ReadyAdvice) GetTipo() string {
	if m != nil {
		return m.Tipo
	}
	return ""
}

func (m *ReadyAdvice) GetUltRet() bool {
	if m != nil {
		return m.UltRet
	}
	return false
}

type Deliver struct {
	Primero              string   `protobuf:"bytes,1,opt,name=primero,proto3" json:"primero,omitempty"`
	Segundo              string   `protobuf:"bytes,2,opt,name=segundo,proto3" json:"segundo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Deliver) Reset()         { *m = Deliver{} }
func (m *Deliver) String() string { return proto.CompactTextString(m) }
func (*Deliver) ProtoMessage()    {}
func (*Deliver) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcfa1b9154291741, []int{6}
}

func (m *Deliver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deliver.Unmarshal(m, b)
}
func (m *Deliver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deliver.Marshal(b, m, deterministic)
}
func (m *Deliver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deliver.Merge(m, src)
}
func (m *Deliver) XXX_Size() int {
	return xxx_messageInfo_Deliver.Size(m)
}
func (m *Deliver) XXX_DiscardUnknown() {
	xxx_messageInfo_Deliver.DiscardUnknown(m)
}

var xxx_messageInfo_Deliver proto.InternalMessageInfo

func (m *Deliver) GetPrimero() string {
	if m != nil {
		return m.Primero
	}
	return ""
}

func (m *Deliver) GetSegundo() string {
	if m != nil {
		return m.Segundo
	}
	return ""
}

func init() {
	proto.RegisterType((*Order)(nil), "proto.Order")
	proto.RegisterType((*Register)(nil), "proto.Register")
	proto.RegisterType((*Packet)(nil), "proto.Packet")
	proto.RegisterType((*QuerySeguimiento)(nil), "proto.QuerySeguimiento")
	proto.RegisterType((*ReplySeguimiento)(nil), "proto.ReplySeguimiento")
	proto.RegisterType((*ReadyAdvice)(nil), "proto.ReadyAdvice")
	proto.RegisterType((*Deliver)(nil), "proto.Deliver")
}

func init() { proto.RegisterFile("logistica.proto", fileDescriptor_dcfa1b9154291741) }

var fileDescriptor_dcfa1b9154291741 = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x41, 0x8e, 0xd3, 0x30,
	0x14, 0x86, 0xe5, 0xb6, 0x49, 0xda, 0x37, 0x68, 0xa8, 0x2c, 0xc4, 0x58, 0x15, 0x8b, 0x2a, 0xab,
	0x11, 0x48, 0xb3, 0x18, 0x58, 0x81, 0x58, 0x20, 0xb1, 0x44, 0x02, 0xdc, 0x03, 0xa0, 0x4c, 0xfc,
	0x54, 0x59, 0x24, 0x76, 0x70, 0x9c, 0x4a, 0x73, 0x0a, 0x2e, 0xc1, 0x01, 0x38, 0x0f, 0xa7, 0x41,
	0x76, 0xec, 0x24, 0x4d, 0x61, 0xd5, 0xfe, 0xcf, 0xf6, 0xff, 0xfe, 0xef, 0x39, 0x86, 0xa7, 0x95,
	0x3e, 0xca, 0xd6, 0xca, 0xb2, 0xb8, 0x6b, 0x8c, 0xb6, 0x9a, 0x26, 0xfe, 0x27, 0xff, 0x49, 0x20,
	0xf9, 0x6c, 0x04, 0x1a, 0x7a, 0x0d, 0x0b, 0x29, 0x18, 0xd9, 0x93, 0xdb, 0x0d, 0x5f, 0x48, 0x41,
	0x77, 0xb0, 0x6e, 0x8c, 0x16, 0x5d, 0x69, 0x35, 0x5b, 0xf8, 0xea, 0xa0, 0xe9, 0x33, 0x48, 0x4e,
	0x45, 0xa5, 0x0d, 0x5b, 0xee, 0xc9, 0xed, 0x92, 0xf7, 0x82, 0x3e, 0x87, 0xd4, 0x4a, 0x54, 0xa2,
	0x60, 0x2b, 0xbf, 0x3f, 0x28, 0xca, 0x20, 0x13, 0xd8, 0x5a, 0xa9, 0x34, 0x4b, 0xfc, 0x42, 0x94,
	0x94, 0xc2, 0xca, 0xca, 0x46, 0xb3, 0xd4, 0x97, 0xfd, 0xff, 0xfc, 0x0f, 0x81, 0x35, 0x47, 0x17,
	0x16, 0x0d, 0x7d, 0x01, 0x1b, 0x2b, 0x6b, 0x6c, 0x6d, 0x51, 0x37, 0x21, 0xdb, 0x58, 0x70, 0x11,
	0xa5, 0xf8, 0x52, 0x94, 0xdf, 0xd1, 0xc6, 0x88, 0x51, 0x0f, 0xd6, 0xcb, 0xd1, 0xda, 0x05, 0x54,
	0xba, 0x7e, 0x30, 0x18, 0x03, 0xf6, 0x6a, 0xc4, 0x49, 0x66, 0x38, 0xda, 0xc8, 0x23, 0xaa, 0x10,
	0x2f, 0xa8, 0x29, 0x4e, 0x76, 0x8e, 0xb3, 0x87, 0xab, 0x16, 0x8f, 0x9d, 0xac, 0x25, 0x2a, 0xab,
	0xd9, 0xda, 0xbb, 0x4d, 0x4b, 0xf9, 0x2f, 0x02, 0x69, 0x08, 0x38, 0x0d, 0x4f, 0x66, 0xe1, 0x67,
	0x46, 0x8b, 0x0b, 0xa3, 0x7f, 0xe2, 0x0d, 0x18, 0xab, 0x29, 0x86, 0xeb, 0xa3, 0xac, 0x3b, 0xd4,
	0x06, 0xbe, 0x41, 0x3b, 0x44, 0x37, 0x4a, 0x11, 0x6f, 0x20, 0xa8, 0xfc, 0x0d, 0x6c, 0xbf, 0x76,
	0x68, 0x1e, 0x0f, 0x93, 0x8e, 0xb3, 0x4c, 0xe4, 0x12, 0xee, 0x25, 0x6c, 0x39, 0x36, 0xd5, 0xd9,
	0xa9, 0xb1, 0x03, 0x39, 0xeb, 0xf0, 0x16, 0xae, 0x38, 0x16, 0xe2, 0xf1, 0x83, 0x38, 0xc9, 0x12,
	0x07, 0x1c, 0x32, 0xc1, 0xb9, 0x81, 0xac, 0xab, 0xec, 0x37, 0x13, 0x2e, 0x77, 0xcd, 0xd3, 0xae,
	0xb2, 0x1c, 0x6d, 0xfe, 0x1e, 0xb2, 0x8f, 0x58, 0xc9, 0x13, 0x1a, 0x77, 0x17, 0x8d, 0x91, 0x35,
	0x9a, 0x78, 0x34, 0x4a, 0xb7, 0xe2, 0xb2, 0x29, 0x11, 0xbf, 0xde, 0x28, 0xef, 0x7f, 0x13, 0xd8,
	0x7e, 0x8a, 0xaf, 0xe1, 0x80, 0xc6, 0x07, 0x78, 0x07, 0x19, 0xc7, 0x1f, 0x1d, 0xb6, 0x96, 0xde,
	0xf4, 0x2f, 0xe4, 0x6e, 0x3e, 0x81, 0x5d, 0x5c, 0xb8, 0x80, 0xbc, 0x87, 0xcd, 0x01, 0x95, 0xe8,
	0xdf, 0xd1, 0x93, 0xb0, 0xcb, 0xab, 0xdd, 0xff, 0xcc, 0xe8, 0x2b, 0x48, 0xfc, 0x00, 0x28, 0x1d,
	0x5c, 0x87, 0x71, 0xec, 0xae, 0x43, 0x2d, 0x60, 0x3e, 0xa4, 0x5e, 0xbe, 0xfe, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0x7f, 0xcf, 0x64, 0x98, 0xc6, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LogisticaServiceClient is the client API for LogisticaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LogisticaServiceClient interface {
	Request(ctx context.Context, in *QuerySeguimiento, opts ...grpc.CallOption) (*ReplySeguimiento, error)
	SendOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*QuerySeguimiento, error)
	Ready(ctx context.Context, in *ReadyAdvice, opts ...grpc.CallOption) (*Deliver, error)
}

type logisticaServiceClient struct {
	cc *grpc.ClientConn
}

func NewLogisticaServiceClient(cc *grpc.ClientConn) LogisticaServiceClient {
	return &logisticaServiceClient{cc}
}

func (c *logisticaServiceClient) Request(ctx context.Context, in *QuerySeguimiento, opts ...grpc.CallOption) (*ReplySeguimiento, error) {
	out := new(ReplySeguimiento)
	err := c.cc.Invoke(ctx, "/proto.LogisticaService/Request", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logisticaServiceClient) SendOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*QuerySeguimiento, error) {
	out := new(QuerySeguimiento)
	err := c.cc.Invoke(ctx, "/proto.LogisticaService/SendOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logisticaServiceClient) Ready(ctx context.Context, in *ReadyAdvice, opts ...grpc.CallOption) (*Deliver, error) {
	out := new(Deliver)
	err := c.cc.Invoke(ctx, "/proto.LogisticaService/Ready", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogisticaServiceServer is the server API for LogisticaService service.
type LogisticaServiceServer interface {
	Request(context.Context, *QuerySeguimiento) (*ReplySeguimiento, error)
	SendOrder(context.Context, *Order) (*QuerySeguimiento, error)
	Ready(context.Context, *ReadyAdvice) (*Deliver, error)
}

// UnimplementedLogisticaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLogisticaServiceServer struct {
}

func (*UnimplementedLogisticaServiceServer) Request(ctx context.Context, req *QuerySeguimiento) (*ReplySeguimiento, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (*UnimplementedLogisticaServiceServer) SendOrder(ctx context.Context, req *Order) (*QuerySeguimiento, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendOrder not implemented")
}
func (*UnimplementedLogisticaServiceServer) Ready(ctx context.Context, req *ReadyAdvice) (*Deliver, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ready not implemented")
}

func RegisterLogisticaServiceServer(s *grpc.Server, srv LogisticaServiceServer) {
	s.RegisterService(&_LogisticaService_serviceDesc, srv)
}

func _LogisticaService_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySeguimiento)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogisticaServiceServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LogisticaService/Request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogisticaServiceServer).Request(ctx, req.(*QuerySeguimiento))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogisticaService_SendOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogisticaServiceServer).SendOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LogisticaService/SendOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogisticaServiceServer).SendOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogisticaService_Ready_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadyAdvice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogisticaServiceServer).Ready(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LogisticaService/Ready",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogisticaServiceServer).Ready(ctx, req.(*ReadyAdvice))
	}
	return interceptor(ctx, in, info, handler)
}

var _LogisticaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.LogisticaService",
	HandlerType: (*LogisticaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _LogisticaService_Request_Handler,
		},
		{
			MethodName: "SendOrder",
			Handler:    _LogisticaService_SendOrder_Handler,
		},
		{
			MethodName: "Ready",
			Handler:    _LogisticaService_Ready_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logistica.proto",
}
